{% set version = "1.6.23" %}

package:
    name: libpng
    version: {{ version }}

source:
    fn: libpng-{{ version }}.tar.gz
    url: ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/libpng-{{ version }}.tar.gz
    sha256: 74a9db9ddd66caa64be82bfcb3cbec4fc4394ceb1053cb7e94b2a0aa9b78eb88

build:
    number: 0
    features:
        - vc9  # [win and py27]
        - vc10  # [win and py34]
        - vc14  # [win and py35]

requirements:
    build:
        - python  # [win]
        - cmake  # [win]
        - libtool  # [not win]
        - automake  # [not win]
        - zlib 1.2.*
    run:
        - zlib 1.2.*

test:
    requires:
        - python {{ environ['PY_VER'] + '*' }}  # [win]
    commands:
        - test -f ${PREFIX}/lib/libpng.a  # [not win]
        - test -f ${PREFIX}/lib/libpng.so  # [linux]
        - test -f ${PREFIX}/lib/libpng.dylib  # [osx]
        - libpng-config --version  # [not win]
        - conda inspect linkages -n _test libpng  # [linux]

about:
    home: http://www.libpng.org/pub/png/libpng.html
    license: Zlib
    summary: PNG reference library
    license_file: libpng-LICENSE.txt

extra:
    recipe-maintainers:
        - ocefpaf
