# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "iGJUDn55V8J56LW8LwpsVofwcEUUXZmr4nzTYy5F5S0JdvD9yunMUgfpL2nk2WnuJScBC4VI8EDP+qk4MfVTIAiMdAxk6jgEcJq114tTowQaMnlWQeyXl2nofJBRUsXVh6Mb8SGVHjuUbVGQ+M38c98iYZuw2o0Q8zjETdv0lyGvyk5wyYI3AlOLYFnwyPzhwE5jhV7uOyhx/CcscG5Dgn8dtf1ExvsxcjMTK7isQZNxdHEfsEAAVFB9l0T2GfqVs+QD4XyVDexmvBUpgje1C2fAA79L1efUNBewVQcFsXOuJAge6x9WHBg7dXcpu0WBh7GgA15rXdcm6Jxt4mDqofR+ntRHWEuoJ6oucPx0uncy4dsG5WeElz2kkb0PLKbL4IQdWV4aVqlJ/taeB54HoIZqw2TOsN1PTltGH/l+Grfg/6D7Ehp8mwy2c7uUOd41Fn21vUQOgfHwixBVzSeiR6gea1PyIGY2nhHRPVwRtbdNfmxhKgOVYYYjjrEXcZc+X54JN79Lu7fGxZdLWNY2NVb3/axUjJyt/qFFU8uLo9Gw0J+3GXQfGEFo2IiBIu7OZzoIs5wA/E75EUWoXF6QbkKAYGLPHlO+mdK4hb1DXFQBxPH4nYBg7TlJbK/WG3UHkYCpead7/6Gjb3JlH71LNX9bHFTTOONirA+aUZ4kAXA="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
