# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "iGJUDn55V8J56LW8LwpsVofwcEUUXZmr4nzTYy5F5S0JdvD9yunMUgfpL2nk2WnuJScBC4VI8EDP+qk4MfVTIAiMdAxk6jgEcJq114tTowQaMnlWQeyXl2nofJBRUsXVh6Mb8SGVHjuUbVGQ+M38c98iYZuw2o0Q8zjETdv0lyGvyk5wyYI3AlOLYFnwyPzhwE5jhV7uOyhx/CcscG5Dgn8dtf1ExvsxcjMTK7isQZNxdHEfsEAAVFB9l0T2GfqVs+QD4XyVDexmvBUpgje1C2fAA79L1efUNBewVQcFsXOuJAge6x9WHBg7dXcpu0WBh7GgA15rXdcm6Jxt4mDqofR+ntRHWEuoJ6oucPx0uncy4dsG5WeElz2kkb0PLKbL4IQdWV4aVqlJ/taeB54HoIZqw2TOsN1PTltGH/l+Grfg/6D7Ehp8mwy2c7uUOd41Fn21vUQOgfHwixBVzSeiR6gea1PyIGY2nhHRPVwRtbdNfmxhKgOVYYYjjrEXcZc+X54JN79Lu7fGxZdLWNY2NVb3/axUjJyt/qFFU8uLo9Gw0J+3GXQfGEFo2IiBIu7OZzoIs5wA/E75EUWoXF6QbkKAYGLPHlO+mdK4hb1DXFQBxPH4nYBg7TlJbK/WG3UHkYCpead7/6Gjb3JlH71LNX9bHFTTOONirA+aUZ4kAXA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
