travis:
  secure:
    BINSTAR_TOKEN: iGJUDn55V8J56LW8LwpsVofwcEUUXZmr4nzTYy5F5S0JdvD9yunMUgfpL2nk2WnuJScBC4VI8EDP+qk4MfVTIAiMdAxk6jgEcJq114tTowQaMnlWQeyXl2nofJBRUsXVh6Mb8SGVHjuUbVGQ+M38c98iYZuw2o0Q8zjETdv0lyGvyk5wyYI3AlOLYFnwyPzhwE5jhV7uOyhx/CcscG5Dgn8dtf1ExvsxcjMTK7isQZNxdHEfsEAAVFB9l0T2GfqVs+QD4XyVDexmvBUpgje1C2fAA79L1efUNBewVQcFsXOuJAge6x9WHBg7dXcpu0WBh7GgA15rXdcm6Jxt4mDqofR+ntRHWEuoJ6oucPx0uncy4dsG5WeElz2kkb0PLKbL4IQdWV4aVqlJ/taeB54HoIZqw2TOsN1PTltGH/l+Grfg/6D7Ehp8mwy2c7uUOd41Fn21vUQOgfHwixBVzSeiR6gea1PyIGY2nhHRPVwRtbdNfmxhKgOVYYYjjrEXcZc+X54JN79Lu7fGxZdLWNY2NVb3/axUjJyt/qFFU8uLo9Gw0J+3GXQfGEFo2IiBIu7OZzoIs5wA/E75EUWoXF6QbkKAYGLPHlO+mdK4hb1DXFQBxPH4nYBg7TlJbK/WG3UHkYCpead7/6Gjb3JlH71LNX9bHFTTOONirA+aUZ4kAXA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
